### ISSUE TITLE
Block Traffic by Country 

### ISSUE THREAD

**Issue by NicoCG** [dustinmoris/Firewall#1]
Hi @dustinmoris ,

Could you kindly provide an example (sample) of Block Traffic by Country and storing configuration in appsettings.json

[How to Block Traffic by Country in the CSF Firewall](https://www.liquidweb.com/kb/how-to-block-traffic-by-country-in-the-csf-firewall/)

It will be a cool feature to add 👍

**Comment by dustinmoris** [comment]
Hi,

There is currently no feature to block traffic by country. It's certainly something that can be added though (wondering why that would be useful though) and an example how to load settings form the appsettings.json is something I'll add over the weekend!

**Comment by NicoCG** [comment]
Thanks @dustinmoris, Blocking countries would be useful because I do not want everyone to use my appliication.

**Comment by dustinmoris** [comment]
I've published a new version which has many improvements and also the capability to filter requests based on the origin country.

**Comment by NicoCG** [comment]
@dustinmoris Thank you
